# Basic details about this repository.

[project]
name = "github.com/rykov/paperboy"
version = "0.1.0"

# Dependencies section lists the packages that are required to build your project.
# Melody uses this information to compute and install all downstream dependencies.
# The keys in this section are the package names and values are version restrictions.
# You can use a specific tagged version, SHA revision, or a version range to narrow
# down what is compatible with your project:
# https://github.com/mdy/melody#specifying-dependency-restrictions
#
# Please note that dependencies are package names as specified in your import
# statements, NOT repository paths.  Although a repository path may exist, you
# will see an error if the root package cannot be imported.

[dependencies]
"github.com/pelletier/go-toml"="head"
"github.com/ghodss/yaml"="head"
"github.com/toorop/go-dkim"="head"
"github.com/spf13/cobra" = "head"
"github.com/spf13/viper"="head"
"github.com/spf13/cast"="head"
"github.com/russross/blackfriday"="head"
"github.com/microcosm-cc/bluemonday"="head"
"github.com/chris-ramon/douceur/inliner"="head"
"github.com/PuerkitoBio/goquery"="head"
"github.com/spf13/afero"="head"
"github.com/bep/inflect"="head"
"github.com/jtacoma/uritemplates"="head"
"github.com/neelance/graphql-go"="head"
"github.com/rs/cors"="head"
"github.com/gholt/blackfridaytext"="head"

# Email libraries for specified purposes
"github.com/jordan-wright/email"="head" # parse/verify
"github.com/go-gomail/gomail"="head" # sign/send

# Testing
"github.com/google/go-cmp/cmp"="head"
